name: .NET

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - uses: nuget/setup-nuget@v1
    - run: nuget install ShipbreakerGameLibs
    - name: Build
      run: dotnet build --no-restore
